In [11]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

'''
import warnings
warnings.filterwarnings(action='ignore')
'''

In [2]:
iris = load_iris()

**Logistic Regression**

In [23]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target, cv = 3)
l_scores

array([0.96078431, 0.92156863, 0.95833333])

In [17]:
np.average(l_scores)

0.9468954248366014

In [31]:
# fancy output of model accuracy (avg and standard deviation):
print("Accuracy: %0.2f (+/- %0.2f)" % (l_scores.mean(), l_scores.std() * 2))

Accuracy: 0.95 (+/- 0.04)


**Decision Tree**

In [26]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv = 3)
d_scores

array([0.98039216, 0.92156863, 1.        ])

In [27]:
np.average(d_scores)

0.9673202614379085

**Support Vector Machine (SVM)**

In [28]:
s_scores = cross_val_score(SVC(), iris.data, iris.target, cv = 3)
s_scores

array([0.98039216, 0.96078431, 0.97916667])

In [8]:
np.average(s_scores)

0.9734477124183006

**Random Forest**

In [29]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv = 3)
r_scores

array([0.98039216, 0.94117647, 0.97916667])

In [10]:
np.average(r_scores)

0.960375816993464

**Best score so far is from SVM: 0.97344771241830064**